config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'

  get 'lists/most_votes', to: 'lists#most_votes'
  get 'users/most_active', to: 'users#most_active'

  resources :lists do
    member { post :favorite, :up_vote, :down_vote }
  end


  resources :users, only: [:new, :create, :show] do
    resources :lists, only: [:new, :create, :show]
  end

  resources :category, only: [:index] do
    resources :lists, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lists
end

app/models/favorite_list.rb
class FavoriteList < ApplicationRecord
  belongs_to :user
  belongs_to :list

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
  validates :desc_link, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true
  has_many :items, before_add: :validate_item_limit
  has_many :favorite_lists
  has_many :favorited_by, through: :favorite_lists, source: :user
  has_many :votes, through: :favorite_lists, source: :user
  validates :name, presence: true
  NUMBER_OF_PERMITTED_ITEMS = 10
  accepts_nested_attributes_for :items
  scope :has_votes, -> { joins(:favorite_lists).where('vote = ?', 1) }
  scope :most_votes, -> { has_votes.group(:list_id).order('count(list_id) DESC').limit(10) }

  def category_name=(name)
    self.category = Category.find_or_create_by(name: name)
  end

  def category_name
    self.category ? self.category.name : nil
  end


  def fav_count
    self.favorited_by.count
  end

  def vote_count
    self.votes.count
  end

  private

  def validate_item_limit(item)
    raise Exception.new if items.size >= NUMBER_OF_PERMITTED_ITEMS
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists
  has_many :favorite_lists
  has_many :favorites, through: :favorite_lists, source: :list
  # has_many :voted_for, through: :favorite_lists, source: :list
  validates :name, presence: true, length: { minimum: 2 }
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i, message: "is invalid" }
  validates :password, presence: true, format: { with: /\A(?=.*[a-zA-Z])(?=.*[0-9]).{6,}\z/, message: "must be at least 6 characters and include one number & one letter"}
  has_secure_password
  scope :most_active, -> {joins(:lists).group(:user_id).order('count(user_id) DESC').first}

  def favorited!(list)
    self.favorites << list
  end

  def unfavorited!(list)
    self.favorites.delete(list)
  end

  def favorited?(list)
    self.favorites.find_by(id: list.id).present?
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :require_logged_in

  def current_user
    @user = (User.find_by(id: session[:user_id]) || User.new)
  end

  def logged_in?
    current_user.id != nil
  end

  def require_logged_in
    return redirect_to login_path unless logged_in?
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :require_logged_in
  skip_before_action :require_logged_in, only: [:index]
  helper_method :redirect_to

  def index
    if params[:category_id]
      @lists = Category.find(params[:category_id]).lists
    else
      @lists = List.all
    end
  end

  def most_votes
    @lists = List.most_votes
  end

  def new
    user_id = current_user.id
    @list = List.new(user_id: user_id)
    10.times do
      @list.items.build
    end
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, notice: "Something went wrong. Try again."
    end
  end

  def show
    @list = List.find(params[:id])
    @user = current_user
  end

  def favorite
    @user = current_user
    @list = List.find(params[:id])
    if @user.favorited?(@list)
      @user.favorites.delete(@list)
      redirect_to list_path(@list), notice: "List has been removed from your favorites."
    else
      @user.favorites << @list
      redirect_to list_path(@list), notice: "List has been added to your favorites."
    end
  end

  def up_vote
    @user = current_user
    @list = List.find(params[:id])
    helpers.u_vote(@user, @list)
  end

  def down_vote
    @user = current_user
    @list = List.find(params[:id])
    helpers.d_vote(@user, @list)
  end

  def destroy
    @user = current_user
    @list = List.find(params[:id])
    if @list.user == @user
      @list.items.delete
      @list.delete
    else
      redirect_to list_path(@list), alert: "Something went wrong. Try again."
    end
    redirect_to user_path(@user), notice: "List has been deleted."
  end

  private

  def list_params
    params.require(:list).permit(:name, :category_name, :user_id, items_attributes: [:desc_link])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if auth
      user = User.find_or_create_by(uid: auth['uid']) do |u|
        u.name = auth['info']['name']
        u.email = auth['info']['email']
        u.image = auth['info']['image']
        u.password = SecureRandom.hex
      end
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      user = User.find_by(name: params[:user][:name])
      user = user.try(:authenticate, params[:user][:password])
      return redirect_to login_path unless user
      @user = user
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    end
  end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    return render :new unless @user.save
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end


  def show
    @user = User.find_by(id: params[:id])
    @lists = @user.lists
    @favs = @user.favorites
  end

  def most_active
    @user = User.most_active
    @lists = @user.lists
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper

  def list_user?(list)
    list.user == current_user
  end

  def u_vote(user, list)
    if user.favorited?(list)
      @fav_vote = FavoriteList.find_by(user_id: user.id, list_id: list.id)
      if @fav_vote.vote == nil || @fav_vote.vote == 0
        @fav_vote.vote = 1
        @fav_vote.save
        redirect_to list_path(list), notice: "Vote recorded!"
      else
        redirect_to list_path(list), alert: "Unable to vote, perhaps you already did."
      end
    else
      redirect_to list_path(list), alert: "You must favorite list to to vote."
    end
  end

  def d_vote(user, list)
    if user.favorited?(list)
      @fav_vote = FavoriteList.find_by(user_id: user.id, list_id: list.id)
      if @fav_vote.vote == 1
        @fav_vote.vote -=1
        @fav_vote.save
        redirect_to list_path(list), notice: "Vote recorded!"
      else
        redirect_to list_path(list), alert: "Unable to vote, perhaps you already did."
      end
    else
      redirect_to list_path(list), alert: "You must favorite list to to vote."
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_button.html.erb
<% if user.favorited?(list) %>
  <%= link_to "UnFav", favorite_list_path(list, type: "unfav"), method: :post, class: "button" %>
<% else %>
  <%= link_to "Fav", favorite_list_path(list, type: "fav"), method: :post, class: "button" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cura10</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<!--[if lte IE 8]><script src="css/ie/html5shiv.js"></script><![endif]-->
		<script src="js/jquery.min.js"></script>
		<script src="js/jquery.dropotron.min.js"></script>
		<script src="js/skel.min.js"></script>
		<script src="js/skel-layers.min.js"></script>
		<script src="js/init.js"></script>
		<noscript>
			<link rel="stylesheet" href="css/skel.css" />
			<link rel="stylesheet" href="css/style.css" />
			<link rel="stylesheet" href="css/style-wide.css" />
		</noscript>
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]-->
  </head>

  <body>
  <!-- Wrapper -->
		<div class="wrapper style1">
    <!-- Header -->
      <div id="header" class="skel-panels-fixed">
        <% if !logged_in? %>
        <div id="logo">
          <h1>Cura10</h1>
          <span class="tag">by CarterBlack Apps</span>
        </div>
        <nav id="nav">
          <ul>
            <li class="active"><%= link_to 'Sign Up', new_user_url %></li>
            <li class="active"><%= link_to 'Log In', login_path %></li>
          </ul>
        </nav>
        <% else %>
        <div id="logo">
          <h1><img src="<%= current_user.image if current_user.image %>" alt=""></h1>
          <span class="tag"><%= current_user.name %></span>
        </div>
        <nav id="nav">
          <ul>
            <li class="active"><%= link_to "Homepage", user_path(current_user) %></li>
            <li class="active"><%= link_to "Feed", lists_path %></li>
            <li class="active"><%= link_to "Cura10 List", new_user_list_path(current_user) %></li>
            <li class="active"><%= link_to "Log Out", logout_path %></li>
          </ul>
        </nav>
        <% end %>
      </div>

      <!-- content -->
    <% if flash[:notice] || flash[:alert] %>
      <div class="container" id="banner"><%= flash[:notice] || flash[:alert] %></div>
    <% end %>

    <%= yield %>

    </div>
  </body>

  <!-- Copyright -->
  	<div id="copyright">
  		<div class="container">
  			<div class="copyright">
  				<p>Design: <a href="http://templated.co">TEMPLATED</a> Images: <a href="http://unsplash.com">Unsplash</a> (<a href="http://unsplash.com/cc0">CC0</a>)</p>
  				<ul class="icons">
  					<li><a href="#" class="fa fa-facebook"><span>Facebook</span></a></li>
  					<li><a href="#" class="fa fa-twitter"><span>Twitter</span></a></li>
  					<li><a href="#" class="fa fa-google-plus"><span>Google+</span></a></li>
  				</ul>
  			</div>
  		</div>
  	</div>
</html>

app/views/lists/_lists_groups.html.erb
<!-- Extra -->
	<div id="extra">
		<div class="container">
			<% lists.in_groups_of(3).each do |l_group| %>
			<div class="row no-collapse-1">
				<% l_group.each do |list| %>
					<% if list %>
					<section class="4u">
						<div class="box">
							<h2><%= list.name %></h2>
							<h3><%= link_to list.category.name.capitalize, category_lists_path(list.category_id) if list.category_id %></h3>
							<h4>Created by: <%= list.user.name if list.user_id %></h4>
							<h5>Votes: <%= list.vote_count %></h5>
							<% list.items.first(3).each do |item| %>
							<ol class="image rnd thumb">
								<li><%= image_tag "#{item.desc_link}" %></li>
							</ol>
							<% end %>
							<%= link_to "Full List", list_path(list), class: "button" if list %>
						</div>
					</section>
					<% end %>
				<% end %>
			</div>
			<% end %>
		</div>
	</div>

app/views/lists/index.html.erb
<!-- Banner -->
	<div id="banner" class="container">
		<section>
			<p>Welcome to <strong>Cura10</strong>! Here you can see all of Cura10's lists from all users. Vote for your favorite by checking out the <strong>Full List</strong> or you can make your own list <strong><%= link_to "here", new_list_path %></strong>.</p>
			<p>Check out our most popular lists with the most votes or our most active user:</p>
			<%= link_to "Most Votes", lists_most_votes_path, class: "button" %>
			<%= link_to "Most Active", users_most_active_path, class: "button" %>
		</section>
	</div>

	<%= render partial: 'lists/lists_groups', locals: {lists: @lists} %>

app/views/lists/most_votes.html.erb
 <%= render partial: 'lists/lists_groups', locals: {lists: @lists} %>

app/views/lists/new.html.erb
<!-- Footer -->
	<div id="banner" class="wrapper style1">
		<div class="container">
			<section>
				<header class="major">
					<h2>Cura10 a list</h2>
					<span class="byline">Add websites or links to create your list</span>
				</header>
				<%= form_for(@list) do |f| %>
					<%= f.hidden_field :user_id %>
					<div class="row half">
						<div class="12u">
							<%= f.text_field :name, placeholder: (@list.errors.full_messages_for(:name).first || "Name") %>
						</div>
					</div>
					<div class="row half">
						<div class="12u">
							<%= f.text_field :category_name, list: "categories_autocomplete", placeholder: "Category" %>
						  <datalist id="categories_autocomplete">
						    <% Category.all.each do |category| %>
						      <option value="<%= category.name.capitalize %>">
						    <% end %>
						  </datalist>
						</div>
					</div>
					<%= f.fields_for :items do |item| %>
					<div class="row half">
						<div class="12u">
							<%= item.text_field :desc_link, placeholder: "Image, Media or Website Link #{item.index + 1}" %>
						</div>
					</div>
					<% end %>
					<div class="row half">
						<div class="12u">
							<ul class="actions">
								<li>
									<%= f.submit %>
								</li>
							</ul>
						</div>
					</div>
				<% end %>
			</section>
		</div>
	</div>

app/views/lists/show.html.erb
<!-- Banner -->
	<div id="banner" class="container">
		<section>
			<h1><strong><%= @list.name %></strong></h1>
      <h2><%= @list.category.name.capitalize if @list.category.name %></h2>
		</section>
	</div>

<!-- Extra -->
  <div id="extra">
    <div class="container">
      <div class="box">
        <% @list.items.each do |item| %>
        <section>
          <ol class="image fit">
            <li><%= image_tag "#{item.desc_link}" %></li>
          </ol>
        </section>
        <% end %>
				<%= render partial: 'favorites/button', locals: {user: current_user, list: @list} %>
				<% if current_user.favorited?(@list) %>
					<%= link_to "up vote", up_vote_list_path(@list), method: :post, class: "button" if !list_user?(@list) %>
					<%= link_to "down vote", down_vote_list_path(@list), method: :post, class: "button" if !list_user?(@list) %>
				<% end %>
				<%= link_to "delete list", list_path(@list), method: :delete, class: "button" if list_user?(@list) %>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<!-- Banner -->
	<div id="banner" class="container">
		<section>
			<p>This is <strong>Phase Shift</strong>, a responsive HTML5 site template freebie by <a href="http://templated.co">TEMPLATED</a>. Released for free under the <a href="http://templated.co/license">Creative Commons Attribution</a> license, so use it for whatever (personal or commercial) &ndash; just give us credit! Check out more of our stuff at <a href="http://templated.co">our site</a> or follow us on <a href="http://twitter.com/templatedco">Twitter</a>.</p>
			<a href="#" class="button medium">Read More</a>
		</section>
	</div>

<!-- Extra -->
	<div id="extra">
		<div class="container">
			<div class="row no-collapse-1">
				<section class="4u"> <a href="#" class="image featured"><img src="images/pic01.jpg" alt=""></a>
					<div class="box">
						<p>Donec leo, vivamus fermentum nibh in augue praesent a lacus at urna congue rutrum  wisi maecenas ligula.</p>
						<a href="#" class="button">Read More</a> </div>
				</section>
				<section class="4u"> <a href="#" class="image featured"><img src="images/pic02.jpg" alt=""></a>
					<div class="box">
						<p>Donec leo, vivamus fermentum nibh in augue praesent a lacus at urna congue rutrum  wisi maecenas ligula.</p>
						<a href="#" class="button">Read More</a> </div>
				</section>
				<section class="4u"> <a href="#" class="image featured"><img src="images/pic03.jpg" alt=""></a>
					<div class="box">
						<p>Donec leo, vivamus fermentum nibh in augue praesent a lacus at urna congue rutrum  wisi maecenas ligula.</p>
						<a href="#" class="button">Read More</a> </div>
				</section>
			</div>
			<div class="row no-collapse-1">
				<section class="4u"> <a href="#" class="image featured"><img src="images/pic01.jpg" alt=""></a>
					<div class="box">
						<p>Donec leo, vivamus fermentum nibh in augue praesent a lacus at urna congue rutrum  wisi maecenas ligula.</p>
						<a href="#" class="button">Read More</a> </div>
				</section>
				<section class="4u"> <a href="#" class="image featured"><img src="images/pic02.jpg" alt=""></a>
					<div class="box">
						<p>Donec leo, vivamus fermentum nibh in augue praesent a lacus at urna congue rutrum  wisi maecenas ligula.</p>
						<a href="#" class="button">Read More</a> </div>
				</section>
				<section class="4u"> <a href="#" class="image featured"><img src="images/pic03.jpg" alt=""></a>
					<div class="box">
						<p>Donec leo, vivamus fermentum nibh in augue praesent a lacus at urna congue rutrum  wisi maecenas ligula.</p>
						<a href="#" class="button">Read More</a> </div>
				</section>
			</div>
		</div>
	</div>

<!-- Main -->
	<div id="main">
		<div class="container">
			<div class="row">

				<!-- Content -->
				<div class="6u">
					<section>
						<ul class="style">
							<li class="fa fa-wrench">
								<h3>Integer ultrices</h3>
								<span>In posuere eleifend odio. Quisque semper augue mattis wisi. Maecenas ligula. Pellentesque viverra vulputate enim. Aliquam erat volutpat. Maecenas condimentum enim tincidunt risus accumsan.</span> </li>
							<li class="fa fa-leaf">
								<h3>Aliquam luctus</h3>
								<span>In posuere eleifend odio. Quisque semper augue mattis wisi. Maecenas ligula. Pellentesque viverra vulputate enim. Aliquam erat volutpat. Maecenas condimentum enim tincidunt risus accumsan.</span> </li>
						</ul>
					</section>
				</div>
				<div class="6u">
					<section>
						<ul class="style">
							<li class="fa fa-cogs">
								<h3>Integer ultrices</h3>
								<span>In posuere eleifend odio. Quisque semper augue mattis wisi. Maecenas ligula. Pellentesque viverra vulputate enim. Aliquam erat volutpat. Maecenas condimentum enim tincidunt risus accumsan.</span> </li>
							<li class="fa fa-road">
								<h3>Aliquam luctus</h3>
								<span>In posuere eleifend odio. Quisque semper augue mattis wisi. Maecenas ligula. Pellentesque viverra vulputate enim. Aliquam erat volutpat. Maecenas condimentum enim tincidunt risus accumsan.</span> </li>
						</ul>
					</section>
				</div>
			</div>
		</div>
	</div>



<!-- Footer -->
	<div id="footer" class="wrapper style2">
		<div class="container">
			<section>
				<header class="major">
					<h2>Mauris vulputate dolor</h2>
					<span class="byline">Integer sit amet pede vel arcu aliquet pretium</span>
				</header>
				<form method="post" action="#">
					<div class="row half">
						<div class="12u">
							<input class="text" type="text" name="name" id="name" placeholder="Name" />
						</div>
					</div>
					<div class="row half">
						<div class="12u">
							<input class="text" type="text" name="email" id="email" placeholder="Email" />
						</div>
					</div>
					<div class="row half">
						<div class="12u">
							<textarea name="message" id="message" placeholder="Message"></textarea>
						</div>
					</div>
					<div class="row half">
						<div class="12u">
							<ul class="actions">
								<li>
									<input type="submit" value="Send Message" class="button alt" />
								</li>
							</ul>
						</div>
					</div>
				</form>
			</section>
		</div>
	</div>

<!-- Copyright -->
	<div id="copyright">
		<div class="container">
			<div class="copyright">
				<p>Design: <a href="http://templated.co">TEMPLATED</a> Images: <a href="http://unsplash.com">Unsplash</a> (<a href="http://unsplash.com/cc0">CC0</a>)</p>
				<ul class="icons">
					<li><a href="#" class="fa fa-facebook"><span>Facebook</span></a></li>
					<li><a href="#" class="fa fa-twitter"><span>Twitter</span></a></li>
					<li><a href="#" class="fa fa-google-plus"><span>Google+</span></a></li>
				</ul>
			</div>
		</div>
	</div>

app/views/users/most_active.html.erb
<!-- Banner -->
	<div id="banner" class="container">
		<section>
			<h1><strong><%= @user.name %> is Cura10's most active user! </strong></h1>
      <h2>Check out their lists below.</h2>
		</section>
	</div>

  <%= render partial: 'lists/lists_groups', locals: {lists: @lists} %>

app/views/users/new.html.erb
<div id="footer" class="wrapper style2">
  <div class="container">
    <section>
      <header class="major">
        <h2>Sign Up Below:</h2>
        <span class="byline"></span>
      </header>
      <%= form_for @user do |f| %>
        <div class="row half">
          <div class="12u">
            <%= f.text_field :name, placeholder: (@user.errors.full_messages_for(:name).first || "Name") %>
          </div>
        </div>
        <div class="row half">
          <div class="12u">
            <%= f.text_field :email, placeholder: (@user.errors.full_messages_for(:email).first || "Email") %>
          </div>
        </div>
        <div class="row half">
          <div class="12u">
            <%= f.password_field :password, placeholder: (@user.errors.full_messages_for(:password).first || "Password") %>
          </div>
        </div>
        <div class="row half">
          <div class="12u">
            <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
          </div>
        </div>
        <div class="row half">
          <div class="12u">
            <ul class="actions">
              <li>
                <%= f.submit "Sign Up!", class: "button alt" %>
              </li>
            </ul>
            <p>OR</p>
          </div>
        </div>
      <% end %>
      <div class="row half">
        <div class="12u">
          <ul class="actions">
            <li>
              <%= link_to('Sign Up with Facebook!', '/auth/facebook', class: "button alt") %>
            </li>
          </ul>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/users/show.html.erb
<!-- Banner -->
	<div id="banner" class="container">
		<section>
			<% if @user.lists.present? %>
				<p>Welcome <strong><%= @user.name %></strong>! See your lists below or check out favorites.</p>
			<% else %>
				<p>Welcome <strong><%= @user.name %></strong>! You have yet to create a list. Let's make one <strong><%= link_to "here", new_list_path %></strong>.</p>
			<% end %>
			<a href="#favs" class="button medium">Favorites</a>
		</section>
	</div>

<!-- Extra -->
	<div id="extra">
		<div class="container">
			<% @lists.in_groups_of(3).each do |l_group| %>
			<div class="row no-collapse-1">
				<% l_group.each do |list| %>
					<% if list %>
					<section class="4u">
						<div class="box">
							<h2><%= list.name %></h2>
							<h3><%= link_to list.category.name.capitalize, category_lists_path(list.category_id) if list.category_id %></h3>
							<% list.items.first(3).each do |item| %>
							<ol class="image rnd thumb">
								<li><%= image_tag "#{item.desc_link}" %></li>
							</ol>
							<% end %>
							<%= link_to "Full List", list_path(list), class: "button" if list %>
						</div>
					</section>
					<% end %>
				<% end %>
			</div>
			<% end %>
		</div>
	</div>
	<br>
	<br>
	<br>

<!-- Favorites -->
	<div id="favs">
		<div id="banner" class="container">
			<section>
				<p><strong>Favorited Lists</strong></p>
			</section>
		</div>
		<div class="container">
			<% @favs.in_groups_of(3).each do |f_group| %>
			<div class="row no-collapse-1">
				<% f_group.each do |list| %>
					<% if list %>
					<section class="4u">
						<div class="box">
							<h2><%= list.name %></h2>
							<h3><%= link_to list.category.name.capitalize, category_lists_path(list.category_id) if list.category_id %></h3>
							<h4>Created by: <%= list.user.name if list.user_id %></h4>
							<% list.items.first(3).each do |item| %>
							<ol class="image rnd thumb">
								<li><%= image_tag "#{item.desc_link}" %></li>
							</ol>
							<% end %>
							<%= link_to "Full List", list_path(list), class: "button" if list %>
						</div>
					</section>
					<% end %>
				<% end %>
			</div>
			<% end %>
		</div>
	</div>